######################################################################
##
## Filename: top_tb.udo
## Created on: Mon Feb 24 22:06:09 中国标准时间 2020
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
